---
namespace: devlbo
name: secrets
version: 1.0.0
readme: README.md

authors:
  - Laurent Bodin

description: >-
  Provision user secrets (passwords, SSH keypairs, passphrases) as
  SOPS-encrypted YAML files using age keys.
  Provides separate roles for passwords and SSH keys.

license_file: LICENSE

tags:
  - secrets
  - sops
  - age
  - encryption
  - passwords
  - ssh
  - security

repository: https://github.com/devlbo/ansible-collection-secrets
documentation: https://github.com/devlbo/ansible-collection-secrets
homepage: https://github.com/devlbo/ansible-collection-secrets
issues: https://github.com/devlbo/ansible-collection-secrets/issues

build_ignore:
  - "*.tar.gz"
  - ".git"
  - ".github"
  - ".gitignore"
  - ".pre-commit-config.yaml"
  - ".venv"
  - ".yamllint"
  - "CODE_OF_CONDUCT.md"
  - "CONTRIBUTING.md"
  - "DEVELOPMENT.md"
  - "Makefile"
  - "docs/"
  - "molecule"
  - "requirements.txt"
  - "requirements-dev.txt"
  - "roles/*/molecule"

dependencies:
  "community.general": ">=11.0.0"
  "community.crypto": ">=2.14.0"
  "community.sops": ">=2.0.0"
  "ansible.posix": ">=2.0.0"
