---
collections:
  - name: community.general
    version: ">=11.0.0"
  - name: community.crypto
    version: ">=2.14.0"
  - name: community.sops
    version: ">=2.0.0"
  - name: ansible.posix
    version: ">=2.0.0"

roles: []
