---
name: Feature Request
description: Suggest a new feature or improvement for the devlbo.secrets collection
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement. Please fill out the fields below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature you are requesting.
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe the problem this feature would solve or the workflow it would enable.
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: >-
        How would you like this feature to work? Include variable names,
        task behavior, or any other relevant details.
    validations:
      required: false
